### ISSUE TITLE
Fallback to entryUUID is not backwards-compatible

### ISSUE THREAD

**Issue by pc-coholic** [Sohalt/pretix-ldap#10]
https://github.com/Sohalt/pretix-ldap/blob/ab40cf9b822910f8d7d22dd3dfd3679ac33362de/src/pretix_ldap/ldap_connector.py#L29

`entryUUID` as well as `unique_attr` did not exist prior to #8.

But if a legacy system is upgraded to the newer version and has neither `unique_attr` or `entryUUID` set, the whole thing will fail.

Perhaps a different field than `entryUUID` should be used as a fallback - one that everyone must have had defined in the past, too?

**Comment by Sohalt** [comment]
Thanks for the report! I've now changed the fallback to `dn`, which should be backwards-compatible.
