### ISSUE TITLE
latest release is quite old

### ISSUE THREAD

**Issue by thebootable** [Sohalt/pretix-ldap#16]
Hi,

I've noticed that the last release is quite old (04/2022).
I can see you tried running a newer release recently but the actions seem to have failed.
Just wondering: Is there anything I can do to help/support you?
I guess a release to pypi would make the whole deployment a lot easier, I'd definitely look forward to it :D 

Just to emphasise: I'm NOT trying to pressure you but genuinly asking if I could be of any help.

Thanks in advance!

**Comment by Sohalt** [comment]
Thank you for raising the issue and offering help.
I developed this plugin in my spare time for an organization I was volunteering at, but I'm no longer using the plugin, so updating it was not a priority.
I finally found the time to update it and hopefully the CI pipeline should keep working like this for the foreseeable future, which will help with accepting PRs and creating releases.
There's a new release that should work with the latest pretix.
