### ISSUE TITLE
Email input is missing on login page

### ISSUE THREAD

**Issue by loelkes** [Sohalt/pretix-ldap#4]
I've followed the instructions here and the [Install a plugin](https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html#updates) at the docs. 

The login page is missing the email input filed. There's no error message visible in the logs.

<img width="406" alt="Screenshot 2020-06-03 at 20 55 07" src="https://user-images.githubusercontent.com/231909/83677670-d26d7b80-a5dc-11ea-93f8-182cc8aa6944.png">

**Comment by Sohalt** [comment]
Can you post your `search_filter`? The login fields should be automatically generated from the placeholders in the `search_filter`.

**Comment by loelkes** [comment]
Oh thanks, I missed that part. Now I have

```
(&(&(objectclass=companyPerson)(memberof=cn=pretix.company.com_login,ou=Services,dc=company,dc=com))(uid={User}))
```
