### ISSUE TITLE
mail attribute needs to be multivalued?

### ISSUE THREAD

**Issue by uschwarz** [Sohalt/pretix-ldap#5]
emails = res[0]['attributes'][self.email_attr]
        if len(emails) != 1:
            return None

From my cursory look (I'm just trying to get it to work at all), in ActiveDirectory mail is single-valued, hence a string, hence it will approximately never have length 1. I added

        if isinstance(emails,str):
            emails = [emails]

and that seemed to help. Also, I understand all the reasons for not showing detailed error messages to the user/attacker, but can we please get errorlog output for the different failure modes (user doesn't exist, user is not unique, mail is not unique, password mismatch, user already exists in different backend)?

**Comment by Sohalt** [comment]
Thanks for the bug report! I don't have an ActiveDirectory to test with and only have tested with openLDAP so far. I've pushed your fix. Can you try if the plugin works from master?

**Comment by YSelfTool** [comment]
We tested master with our AD (Samba). Except for a missing `s` (`email` -> `emails`) it works fine.

**Comment by Sohalt** [comment]
@YSelfTool thank you!
